In [1]:
import pandas as pd
import numpy as np
import re
import os

# Load the raw IPO data
df = pd.read_csv("../data/raw/ipo_2010_2021.csv")
df_nifty = pd.read_csv("../data/raw/NIFTY_2010_2021.csv")

print(f"IPO shape: {df.shape}")
print(f"NIFTY shape: {df_nifty.shape}")
print("\nIPO Columns:", list(df.columns))

IPO shape: (264, 14)
NIFTY shape: (2873, 7)

IPO Columns: ['Date', 'IPO Name', 'Profile', 'Issue Size (in crores)', 'QIB', 'HNI', 'RII', 'Total', 'Issue', 'Listing Open', 'Listing Close', 'Listing Gains(%)', 'CMP', 'Current  Gains (%)']


In [2]:
print("=== MISSING VALUES ===")
print(df.isnull().sum())

print("\n=== DATA TYPES ===")
print(df.dtypes)

print("\n=== BASIC STATS ===")
df.describe()

=== MISSING VALUES ===
Date                      0
IPO Name                  0
Profile                   0
Issue Size (in crores)    0
QIB                       0
HNI                       0
RII                       0
Total                     0
Issue                     0
Listing Open              0
Listing Close             0
Listing Gains(%)          0
CMP                       0
Current  Gains (%)        2
dtype: int64

=== DATA TYPES ===
Date                       object
IPO Name                   object
Profile                    object
Issue Size (in crores)    float64
QIB                       float64
HNI                       float64
RII                       float64
Total                     float64
Issue                     float64
Listing Open              float64
Listing Close             float64
Listing Gains(%)          float64
CMP                        object
Current  Gains (%)        float64
dtype: object

=== BASIC STATS ===


,Issue Size (in crores),QIB,HNI,RII,Total,Issue,Listing Open,Listing Close,Listing Gains(%),Current Gains (%)
count,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,264.000000,262.00000
mean,978.718106,23.732841,68.798561,7.388371,25.944886,339.291667,403.329735,363.170152,4.290871,57.14145
std,1884.758112,36.880595,136.513479,11.837761,45.444680,333.874356,437.396998,417.120358,46.343783,240.46593
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.500000,1.570000,-97.150000,-99.93000
25%,144.250000,1.130000,1.210000,1.297500,1.570000,109.500000,117.750000,93.025000,-11.755000,-80.50500
50%,441.225000,4.670000,5.075000,3.380000,4.845000,220.000000,251.300000,208.225000,1.355000,-3.92500
75%,903.187500,32.505000,65.112500,8.392500,33.412500,447.000000,546.250000,520.425000,25.635000,94.58000
max,15475.000000,176.850000,958.070000,77.930000,277.280000,1766.000000,2725.000000,3118.650000,153.500000,2500.14000


In [3]:
print("=== SAMPLE RAW VALUES ===")

# Check each column for messy values
for col in df.columns:
    print(f"\n{col}:")
    print(df[col].dropna().unique()[:5])

=== SAMPLE RAW VALUES ===

Date:
['29-07-21' '23-07-21' '19-07-21' '07-07-21' '05-07-21']

IPO Name:
['Tatva Chintan' 'Zomato' 'Clean Science' 'G R Infra' 'India Pesticide']

Profile:
['https://www.moneycontrol.com/ipo/tatva-chintan_TCP02.html'
 'https://www.moneycontrol.com/ipo/zomato_Z01.html'
 'https://www.moneycontrol.com/ipo/clean-science_CST.html'
 'https://www.moneycontrol.com/ipo/g-r-infra_I13.html'
 'https://www.moneycontrol.com/ipo/india-pesticide_IP09.html']

Issue Size (in crores):
[ 500.   9375.   1546.    963.28  800.  ]

QIB:
[  2.55  51.79 156.37  93.18   2.64]

HNI:
[  9.78  32.96 206.43  73.01   1.36]

RII:
[13.36  7.45  9.    4.89  4.4 ]

Total:
[ 9.5  38.25 93.41 43.48  3.25]

Issue:
[1083.   76.  900.  837.  296.]

Listing Open:
[2111.8  115.  1784.4 1700.   360. ]

Listing Close:
[2310.25  125.85 1585.2  1746.8   335.45]

Listing Gains(%):
[113.32  65.59  76.13 108.7   13.33]

CMP:
['2,268.50' '133.35' '1,682.80' '1,730.85' '337.40']

Current  Gains (%):
[109.46  

In [4]:
print("=" * 60)
print("MISSING VALUES")
print("=" * 60)
print(df.isnull().sum())

print("\n" + "=" * 60)
print("DATA TYPES")
print("=" * 60)
print(df.dtypes)

print("\n" + "=" * 60)
print("UNIQUE SAMPLE VALUES PER COLUMN")
print("=" * 60)
for col in df.columns:
    print(f"\n[ {col} ]")
    print(df[col].dropna().unique()[:5])

MISSING VALUES
Date                      0
IPO Name                  0
Profile                   0
Issue Size (in crores)    0
QIB                       0
HNI                       0
RII                       0
Total                     0
Issue                     0
Listing Open              0
Listing Close             0
Listing Gains(%)          0
CMP                       0
Current  Gains (%)        2
dtype: int64

DATA TYPES
Date                       object
IPO Name                   object
Profile                    object
Issue Size (in crores)    float64
QIB                       float64
HNI                       float64
RII                       float64
Total                     float64
Issue                     float64
Listing Open              float64
Listing Close             float64
Listing Gains(%)          float64
CMP                        object
Current  Gains (%)        float64
dtype: object

UNIQUE SAMPLE VALUES PER COLUMN

[ Date ]
['29-07-21' '23-07-21' '19-07-21' '

In [5]:
print(df.isnull().sum())

Date                      0
IPO Name                  0
Profile                   0
Issue Size (in crores)    0
QIB                       0
HNI                       0
RII                       0
Total                     0
Issue                     0
Listing Open              0
Listing Close             0
Listing Gains(%)          0
CMP                       0
Current  Gains (%)        2
dtype: int64


In [6]:
print(df.dtypes)

Date                       object
IPO Name                   object
Profile                    object
Issue Size (in crores)    float64
QIB                       float64
HNI                       float64
RII                       float64
Total                     float64
Issue                     float64
Listing Open              float64
Listing Close             float64
Listing Gains(%)          float64
CMP                        object
Current  Gains (%)        float64
dtype: object


In [7]:
for col in df.columns:
    print(f"\n[ {col} ]")
    print(df[col].dropna().unique()[:5])


[ Date ]
['29-07-21' '23-07-21' '19-07-21' '07-07-21' '05-07-21']

[ IPO Name ]
['Tatva Chintan' 'Zomato' 'Clean Science' 'G R Infra' 'India Pesticide']

[ Profile ]
['https://www.moneycontrol.com/ipo/tatva-chintan_TCP02.html'
 'https://www.moneycontrol.com/ipo/zomato_Z01.html'
 'https://www.moneycontrol.com/ipo/clean-science_CST.html'
 'https://www.moneycontrol.com/ipo/g-r-infra_I13.html'
 'https://www.moneycontrol.com/ipo/india-pesticide_IP09.html']

[ Issue Size (in crores) ]
[ 500.   9375.   1546.    963.28  800.  ]

[ QIB ]
[  2.55  51.79 156.37  93.18   2.64]

[ HNI ]
[  9.78  32.96 206.43  73.01   1.36]

[ RII ]
[13.36  7.45  9.    4.89  4.4 ]

[ Total ]
[ 9.5  38.25 93.41 43.48  3.25]

[ Issue ]
[1083.   76.  900.  837.  296.]

[ Listing Open ]
[2111.8  115.  1784.4 1700.   360. ]

[ Listing Close ]
[2310.25  125.85 1585.2  1746.8   335.45]

[ Listing Gains(%) ]
[113.32  65.59  76.13 108.7   13.33]

[ CMP ]
['2,268.50' '133.35' '1,682.80' '1,730.85' '337.40']

[ Current  Gains

In [8]:
import pandas as pd
import numpy as np
import os

df = pd.read_csv("../data/raw/ipo_2010_2021.csv")
df_nifty = pd.read_csv("../data/raw/NIFTY_2010_2021.csv")

print(f"Original shape: {df.shape}")
print("Loaded successfully!")

Original shape: (264, 14)
Loaded successfully!


In [9]:
# Profile column is just URLs — no value for ML
df = df.drop(columns=["Profile"])

print("Dropped Profile column")
print(f"New shape: {df.shape}")
print(f"Columns remaining: {list(df.columns)}")

Dropped Profile column
New shape: (264, 13)
Columns remaining: ['Date', 'IPO Name', 'Issue Size (in crores)', 'QIB', 'HNI', 'RII', 'Total', 'Issue', 'Listing Open', 'Listing Close', 'Listing Gains(%)', 'CMP', 'Current  Gains (%)']


In [10]:
# Date is in format '29-07-21' — convert to proper datetime
df["Date"] = pd.to_datetime(df["Date"], format="%d-%m-%y")

# Extract useful time features from date
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month
df["Quarter"] = df["Date"].dt.quarter

print("Date column fixed!")
print(df["Date"].head())
print(f"\nYear range: {df['Year'].min()} to {df['Year'].max()}")

Date column fixed!
0   2021-07-29
1   2021-07-23
2   2021-07-19
3   2021-07-19
4   2021-07-07
Name: Date, dtype: datetime64[ns]

Year range: 2010 to 2021


In [11]:
# CMP has commas like "2,268.50" — remove commas and convert to float
df["CMP"] = df["CMP"].astype(str).str.replace(",", "", regex=False)
df["CMP"] = pd.to_numeric(df["CMP"], errors="coerce")

print("CMP column fixed!")
print(f"CMP dtype: {df['CMP'].dtype}")
print(f"Sample values: {df['CMP'].dropna().head().values}")

CMP column fixed!
CMP dtype: float64
Sample values: [2268.5   133.35 1682.8  1730.85  337.4 ]


In [12]:
# Rename columns to clean snake_case — easier to work with in code
df = df.rename(columns={
    "IPO Name"              : "ipo_name",
    "Issue Size (in crores)": "issue_size_cr",
    "QIB"                   : "qib_subscription",
    "HNI"                   : "hni_subscription",
    "RII"                   : "rii_subscription",
    "Total"                 : "total_subscription",
    "Issue"                 : "issue_price",
    "Listing Open"          : "listing_open",
    "Listing Close"         : "listing_close",
    "Listing Gains(%)"      : "listing_gains_pct",
    "CMP"                   : "cmp",
    "Current Gains (%)"     : "current_gains_pct"
})

print("Columns renamed!")
print(list(df.columns))

Columns renamed!
['Date', 'ipo_name', 'issue_size_cr', 'qib_subscription', 'hni_subscription', 'rii_subscription', 'total_subscription', 'issue_price', 'listing_open', 'listing_close', 'listing_gains_pct', 'cmp', 'Current  Gains (%)', 'Year', 'Month', 'Quarter']


In [13]:
print("Missing values before treatment:")
print(df.isnull().sum())

# Fill missing subscription values with median
for col in ["qib_subscription", "hni_subscription",
            "rii_subscription", "total_subscription"]:
    median_val = df[col].median()
    df[col] = df[col].fillna(median_val)
    print(f"Filled {col} nulls with median: {median_val:.2f}")

# Fill missing CMP with listing_close (best approximation)
df["cmp"] = df["cmp"].fillna(df["listing_close"])

print("\nMissing values after treatment:")
print(df.isnull().sum())

Missing values before treatment:
Date                  0
ipo_name              0
issue_size_cr         0
qib_subscription      0
hni_subscription      0
rii_subscription      0
total_subscription    0
issue_price           0
listing_open          0
listing_close         0
listing_gains_pct     0
cmp                   0
Current  Gains (%)    2
Year                  0
Month                 0
Quarter               0
dtype: int64
Filled qib_subscription nulls with median: 4.67
Filled hni_subscription nulls with median: 5.08
Filled rii_subscription nulls with median: 3.38
Filled total_subscription nulls with median: 4.84

Missing values after treatment:
Date                  0
ipo_name              0
issue_size_cr         0
qib_subscription      0
hni_subscription      0
rii_subscription      0
total_subscription    0
issue_price           0
listing_open          0
listing_close         0
listing_gains_pct     0
cmp                   0
Current  Gains (%)    2
Year                  0
Month  

In [14]:
# Absolute listing gain in rupees
df["listing_gain_abs"] = df["listing_close"] - df["issue_price"]

# Categorize IPOs by listing performance
def categorize_gain(pct):
    if pct < 0:
        return "Loss"
    elif pct < 10:
        return "Weak"
    elif pct < 30:
        return "Moderate"
    elif pct < 50:
        return "Strong"
    else:
        return "Blockbuster"

df["performance_category"] = df["listing_gains_pct"].apply(categorize_gain)

print("New columns added!")
print(df[["ipo_name", "listing_gains_pct",
          "performance_category"]].head(10))

New columns added!
          ipo_name  listing_gains_pct performance_category
0    Tatva Chintan             113.32          Blockbuster
1           Zomato              65.59          Blockbuster
2    Clean Science              76.13          Blockbuster
3        G R Infra             108.70          Blockbuster
4  India Pesticide              13.33             Moderate
5    Krishna Inst.              32.95               Strong
6      Dodla Dairy              42.31               Strong
7   Shyam Metalics              22.83             Moderate
8         Sona BLW              24.69             Moderate
9  PowerGrid InvIT               2.98                 Weak


In [15]:
# Fix NIFTY date column
df_nifty["Date"] = pd.to_datetime(df_nifty["Date"])

# Rename columns
df_nifty = df_nifty.rename(columns={
    "Open"              : "nifty_open",
    "High"              : "nifty_high",
    "Low"               : "nifty_low",
    "Close"             : "nifty_close",
    "Shares Traded"     : "shares_traded",
    "Turnover (Rs. Cr)" : "turnover_cr"
})

# Calculate 30-day rolling return on Nifty
df_nifty = df_nifty.sort_values("Date").reset_index(drop=True)
df_nifty["nifty_30d_return"] = df_nifty["nifty_close"].pct_change(30) * 100

print("NIFTY dataset cleaned!")
print(df_nifty.head(3))

NIFTY dataset cleaned!
        Date  nifty_open  nifty_high  nifty_low  nifty_close  shares_traded  \
0 2010-01-04     5200.90     5238.45    5167.10       5232.2      148652424   
1 2010-01-05     5277.15     5288.35    5242.40       5277.9      240844424   
2 2010-01-06     5278.15     5310.85    5260.05       5281.8      216147837   

   turnover_cr  nifty_30d_return  
0      6531.61               NaN  
1      7969.62               NaN  
2      7892.60               NaN  


In [16]:
# Match each IPO date with the Nifty 30-day return
# This tells us: what was the market mood when this IPO listed?
df = df.sort_values("Date").reset_index(drop=True)

df_merged = pd.merge_asof(
    df,
    df_nifty[["Date", "nifty_close", "nifty_30d_return"]],
    on="Date",
    direction="nearest"
)

print(f"Merged shape: {df_merged.shape}")
print(f"\nSample — IPO with market context:")
df_merged[["ipo_name", "listing_gains_pct",
           "nifty_close", "nifty_30d_return"]].head(5)

Merged shape: (264, 20)

Sample — IPO with market context:


,ipo_name,listing_gains_pct,nifty_close,nifty_30d_return
0,Infinite Comp,11.82,4931.85,NaN
1,Jubilant Food,-21.03,4760.40,NaN
2,Vascon Engineer,-11.28,4801.95,NaN
3,Syncom Health,17.13,4801.95,NaN
4,Thangamayil,-5.20,4844.90,-7.945887


In [17]:
os.makedirs("../data/cleaned", exist_ok=True)

df_merged.to_csv("../data/cleaned/ipo_cleaned.csv", index=False)

print("Cleaned data saved!")
print(f"Final shape: {df_merged.shape}")
print(f"Final columns: {list(df_merged.columns)}")

Cleaned data saved!
Final shape: (264, 20)
Final columns: ['Date', 'ipo_name', 'issue_size_cr', 'qib_subscription', 'hni_subscription', 'rii_subscription', 'total_subscription', 'issue_price', 'listing_open', 'listing_close', 'listing_gains_pct', 'cmp', 'Current  Gains (%)', 'Year', 'Month', 'Quarter', 'listing_gain_abs', 'performance_category', 'nifty_close', 'nifty_30d_return']


In [18]:
# Load the cleaned file
df = pd.read_csv("../data/cleaned/ipo_cleaned.csv")

print("Before fixing zeros:")
print(f"Rows with issue_price = 0: {(df['issue_price'] == 0).sum()}")
print(f"Rows with issue_size_cr = 0: {(df['issue_size_cr'] == 0).sum()}")

# Remove rows where issue_price or issue_size_cr is 0
# These are incomplete records — useless for ML
df = df[df["issue_price"] > 0]
df = df[df["issue_size_cr"] > 0]

print("\nAfter fixing zeros:")
print(f"Rows with issue_price = 0: {(df['issue_price'] == 0).sum()}")
print(f"Rows with issue_size_cr = 0: {(df['issue_size_cr'] == 0).sum()}")
print(f"\nFinal shape after cleaning: {df.shape}")

Before fixing zeros:
Rows with issue_price = 0: 2
Rows with issue_size_cr = 0: 3

After fixing zeros:
Rows with issue_price = 0: 0
Rows with issue_size_cr = 0: 0

Final shape after cleaning: (259, 20)


In [19]:
df.to_csv("../data/cleaned/ipo_cleaned.csv", index=False)
print("Cleaned file updated and saved!")

Cleaned file updated and saved!


In [20]:
import pandas as pd

df = pd.read_csv("../data/validated/ipo_validated.csv")
df["Date"] = pd.to_datetime(df["Date"])

# Add readable month name for Power BI
month_map = {1:"Jan",2:"Feb",3:"Mar",4:"Apr",5:"May",6:"Jun",
             7:"Jul",8:"Aug",9:"Sep",10:"Oct",11:"Nov",12:"Dec"}
df["Month_Name"] = df["Month"].map(month_map)

# Save to powerbi folder
df.to_csv("../powerbi/ipo_powerbi.csv", index=False)
print("Exported to powerbi/ipo_powerbi.csv!")
print(f"Shape: {df.shape}")

Exported to powerbi/ipo_powerbi.csv!
Shape: (259, 21)
